### ISSUE TITLE
Error Stacktrace

### ISSUE THREAD

**Issue by dzove855** [hyperupcall/bash-core#2]
You could add something like an Errstacktrace

On of my projects.
(https://github.com/yoctu/yosh/blob/master/lib/cli.sh#L60)

It would look like this
`/home/dzove855/yosh2/lib/marco.sh: line 4: tik: command not found
Error in /home/dzove855/yosh2/lib/marco.sh:4. 'tik' exited with status 127
Call tree:
 1: /home/dzove855/yosh2/lib/cli.sh:8 Marco::run(...)
 2: yosh2/bin/yosh-runner.sh:78 Cli::router(...)
Exiting with status 1`

And then you just need to trap ERR so the stackstrace qwill always be call'd when an error happens.

**Comment by dzove855** [comment]
Okei i see. 

Actually you could write a function where you can register some other functions they will be called on exit or ERR. 

Example:
```error::handler::append FUNCTIONAME1
error::handler::append FUNCTIONAME2
trap 'error::handler' EXIT
trap 'error::handler' ERR
```
and add a error::handler::overwrite FUNCTIONAME1
which will overwrite the functions that are in the handler. This could allow you to have some custom handlers differently for handled error messages and unhandled.

**Comment by hyperupcall** [comment]
Commit 85553a18acd74f5dbbe7212e0acba0d8d5b6c1b7 added stacktrace printing! The printing looks like the ones by Node/Ruby/Python  so it should be familiar.

Thanks for your feedback btw :), I wish I got around to this sooner

**Comment by dzove855** [comment]
Great. Note that the stacktrace and trap sometimes doesn't work. I could not explain why and i didn't invistigate a lpt about the issue

**Comment by hyperupcall** [comment]
> Note that the stacktrace and trap sometimes doesn't work

Like specific to this repo? Gosh I'll have to take a look

**Comment by dzove855** [comment]
Not really specific to this repo. But more in my case of my repo i have linked. But it has been a long time since i didn't had a look.

**Comment by hyperupcall** [comment]
Gotchia gotchia, thanks for letting me know!
